apiVersion: v1
kind: Pod
metadata:
   name: mypod3
spec:
   containers:
   - name: tomcat
     image: tomcat
   - name: database
     image: bitnami/mongodb   
   - name: myhttpd
     image: httpd    
